TRUNCATE TABLE pos_sale_invoicehdr;
TRUNCATE TABLE pos_sale_invoicedtl;
TRUNCATE TABLE pos_sale_paymode;
TRUNCATE TABLE journaldetails;
TRUNCATE TABLE pos_sale_deletelog;
TRUNCATE TABLE pos_payout_dtl;
UPDATE POS_MASTER SET PM_TRANS_NO =0;
select * from pos_sale_invoicehdr;
select * from pos_sale_invoicedtl;
select * from pos_sale_paymode;
https://myposqr.com/retailbilling/controller/getfunctionmgmt.php?EmployeeReq=1&json={"emp_id":"0","emp_firstname":"RAVI","emp_lastname":"RAMALINGAM","emp_printname":"RAVIKUMAR","emp_idtype":"NRIC","emp_passportic":"1","emp_nationality":"MALAYSIA","emp_passexpire":"2025/08/27","emp_visaexpire":"2025/08/27","emp_joindate":"2025/08/27","emp_resigndate":"1111-11-11","emp_contactno":"-","emp_contactname":"-","emp_emergencyno":"-","emp_compid":"1","emp_locid":"2","emp_designation":"CASHIER","emp_bankname":"-","emp_accountname":"-","emp_accountno":"0","emp_image":"X","emp_basicsalary":"0.00","emp_basicrate":"0.00","emp_otrate":"0.00","emp_othrsrate":"0.00","emp_allowance":"0.00","emp_currentstatus":"Working","emp_remarks":"-","emp_active":"1","emp_epf":"00.0","emp_socso":"00.0","emp_dob":"2025/08/27","emp_monthexpire":"Aug-2025","emp_curpermit":"-","emp_nextpermit":"-"}
